development:
  adapter: mysql
  encoding: utf8
  database: fushang318_test_development
  username: root
  password: root
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  database: fushang318_test_test
  username: root
  password: root
  host: localhost
